import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi'
import Head from 'next/head';
import styles from './Home.module.css';
import { init, useLazyQuery } from "@airstack/airstack-react";
import dynamic from 'next/dynamic';
import AccountComponent from '@/components/AccountComponent/AccountComponent';
import Menubar from '@/components/Navbar/Menubar';
init("59b3109f040748f9b4a038900c6fd3d5");

const NFTComponent = dynamic(() => import('@/components/NFTComponent/NFTComponent'), { ssr: false })

const Home = () => {

  const account = useAccount({
    onConnect({ address, connector, isReconnected }) {
      console.log('Connected', { address, connector, isReconnected })
    },
  })

  const [tokenDetails, setTokenDetails] = useState({});
  const [TBAccounts, setTBAccounts] = useState([])
  const [NFTS, setNFTS] = useState([])
  const [isNexted, setIsNexted] = useState(false)
  
  const nexted = () => {
    setIsNexted(true)
  }

  const resetPage = () => {
    setTokenDetails({});
    setTBAccounts([]);
    setIsNexted(false);
  };
  
  const variables = {
    "address": `${account.address}`,
  };
  
  const NFTFetch = `query tokens($address: Identity!) {
    erc721: TokenBalances(
      input: {blockchain: polygon, filter: {owner: {_in: [$address]}, tokenType: {_in: [ERC721]}}}
      ) {
        data:TokenBalance {
          amount
          chainId
          id
          tokenAddress
          tokenId
      tokenType
      token {
        name
        symbol
      }
      tokenNfts {
        tokenId
        metaData {
          name
        }
        contentValue {
          image {
            medium
            extraSmall
            large
            original
            small
          }
        }
      }
    }
  }
}`


const TBAQuery = `query MyQuery($tokenAddress: Address, $tokenId: String) {
  Accounts(
    input: {blockchain: polygon, limit: 200, filter: {tokenAddress: {_eq: $tokenAddress}, tokenId: {_eq: $tokenId}}}
    ) {
      Account {
        address {
          addresses
          domains {
            name
            isPrimary
          }
          socials {
            dappName
            profileName
          }
        }
        implementation
      }
    }
  }`;

  console.log(tokenDetails.address)
  
  const [fetchTba, response] = useLazyQuery(TBAQuery);

  const [fetch, { data, loading, error }] = useLazyQuery(NFTFetch, variables);
  
  useEffect(() => {
    if (tokenDetails && isNexted) {
      fetchTba({    
      "tokenAddress": `${tokenDetails.address}`,
      "tokenId": `${tokenDetails.Id}` 
    } );
    }
  }, [tokenDetails, isNexted])
  
  useEffect(() => {
    if (response.data != null) {
      setTBAccounts(response.data.Accounts.Account)
    }
  }, [response]);

  useEffect(() => {
    if (account.address) {
      fetch()
    }
  },[account.address])

  useEffect(() => {
    if (data && data.erc721 && data.erc721.data) {
      console.log(data)
      setNFTS(data.erc721.data)
    }
  }, [data])

  const handleAddressChange = (e) => {
    setTokenDetails({...tokenDetails, address: e.target.value})
  }

  const handleTokenIdChange = (e) => {
    setTokenDetails({...tokenDetails, Id: e.target.value})
  }

  const handleFormSubmit = (e) => {
    e.preventDefault();
    nexted()
  };

  console.log(tokenDetails)

  return (
    <Menubar resetPage={resetPage}>
    <div className={styles.container}>
      <Head>
        <title>TBA Easier</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

        <div className={styles.inputSec}>
          You can connect your wallet to find your NFTs, or you can directly search for spesific NFT.
          <form onSubmit={handleFormSubmit}>
            NFT Address: <input key={tokenDetails.address} value={tokenDetails.address} onChange={handleAddressChange} placeholder='Contract address' className={styles.inputBox}  />
            Token Id: <input key={tokenDetails.Id} value={tokenDetails.Id} onChange={handleTokenIdChange} placeholder='Token Id' className={styles.inputBox}  />
            <button className={styles.buttonx}>Find Em</button>
          </form>
        </div>

        {NFTS.length > 0 && (
          (tokenDetails && isNexted) ? (
            TBAccounts.map((acc, index) => (
              <AccountComponent key={index} acc={acc}/>
            ))
          ) : (
            <>
          <div className={styles.nftGallery}>
            {NFTS.map((nft, index) => (
              <div key={index}>
                <NFTComponent nfts={nft} setTokenDetails={setTokenDetails} />
              </div>
            ))}
          </div>
              </>
            ))
          }
        
        

      <footer className={styles.footer}>
        <a href="https://github.com/oguzutku1745" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by KyaTzu
        </a>
      </footer>
    </div>
    </Menubar>
  );
};

export default Home;
